### ISSUE TITLE
could you provide docs or just a basic example on how to use it?

### ISSUE THREAD

**Issue by maxandersen** [abcminiuser/python-homeassistant-streamdeck#4]
would love to make good of my elgato stream deck and homeassistant would be a good place. Would love to try it out but not sure where to start - any chance you have a configuration.yaml example to start with ? 

thanks!

**Comment by Br3nda** [comment]
There is an example config.yml in the src folder

**Comment by abcminiuser** [comment]
As @Br3nda says, I've put my own config file in the `src` directory - it's not documented, but hopefully it shouldn't be too hard to figure out (you'll probably want to just edit the `home_assistant` and `screens` sections).
